export EDITOR=vim
export LANG=en_US.UTF-8

if [ -e "$ZDOTDIR/local.zsh" ]; then
    source "$ZDOTDIR/local.zsh"
fi

source "$ZDOTDIR/appearance.zsh"
source "$ZDOTDIR/behavior.zsh"
source "$ZDOTDIR/completion.zsh"
source "$ZDOTDIR/key-bindings.zsh"

# override builtin functions (preexec, precmd, etc.)
source "$ZDOTDIR/function-overrides.zsh"

# user bin should take absolute priority
export PATH="$HOME/bin:$PATH"
